### ISSUE TITLE
Regarding committing new files

### ISSUE THREAD

**Issue by FantaX1911** [P3D-Legacy/P3D-Legacy-Old#12]
When I commit new files, do I need to edit "2.5DHero.vbproj" and add something like "Compile Include="Blah\blah\newfile.vb""
or how does that work?

**Comment by jianmingyong** [comment]
Yea, you will need to add that in order for it to be included in the project.

**Comment by nilllzz** [comment]
You need to include it with a "compile" option if it is a .vb file, so the compile knows to include it in the compilation.
For .dat files in the maps and scripts folder, as well as trainer and poke files, you don't need to add them manually because they are included with a wildcard.

**Comment by Aragas** [comment]
Ja.

**Comment by FantaX1911** [comment]
Yea, that makes sense, thanks.
