### ISSUE TITLE
wiki for the game?

### ISSUE THREAD

**Issue by masterchiller96** [P3D-Legacy/P3D-Legacy-Old#16]
the wiki for this game has not been updated for months, what can we do about this?

**Comment by CaptainSegis** [comment]
Might get someone to slowly update it over time.

**Comment by masterchiller96** [comment]
could we also transfer it to another host like wikia?

**Comment by CaptainSegis** [comment]
why should that be done?

**Comment by chillgamingAZ** [comment]
I say this because no one ever visits the old site anymore
