### ISSUE TITLE
Servers And loading Crash

### ISSUE THREAD

**Issue by MeCodeMyself** [P3D-Legacy/P3D-Legacy-Old#18]
How Do I access servers I haven't found out a way to do it yet and do I  just use the source code if yes how?

**Comment by CaptainSegis** [comment]
What do you mean? You want to play the game in a already existing server?

**Comment by MeCodeMyself** [comment]
I meant how do you make one I put in my IP and everything

**Comment by jianmingyong** [comment]
You will need to host a server using the server application to join using your own ip.

But we welcome you to join our public server: p3d.aggressivegaming.org:15124

**Comment by MeCodeMyself** [comment]
Thx well How do I get the server application

**Comment by MeCodeMyself** [comment]
I also have a problem with loading screen for online first it takes forever second  it always crashes when it doesn't work  but it does work sometimes that's why I asked on info for the server thing

**Comment by jianmingyong** [comment]
Gamejolt isn't enabled in the source code. Technically it doesn't work.
Server application can be built manually or download from http://pokemon3d.net/forum/resources/153/

**Comment by MeCodeMyself** [comment]
I can't get the server app because the website won't send me verification email

**Comment by jianmingyong** [comment]
Try this:

http://pokemon.aggressivegaming.org/resources/pokemon-3d-server-client.4/

**Comment by MeCodeMyself** [comment]
Thx I'm also downloading the Pokemon 3D 74 it said it was released 8 hours ago so I guess it's going to be good

**Comment by jianmingyong** [comment]
Since problem is resolved, might as well close this issue.
